### ISSUE TITLE
GNSS location test error

### ISSUE THREAD

**Issue by enddls** [Lora-net/lora_edge_tracker_ref_design#5]
hi

I try to test Lr1110 tracker with actility and tagoio.

I check test wifi location during day.

but I can't check gnss location.

lr1110 was set at under picture.
![KakaoTalk_20210706_205920309](https://user-images.githubusercontent.com/72924662/124596333-1cd6c100-de9d-11eb-8bd6-f5e08524cdf6.jpg)

and this is data traffic history of tagoio
[Data flow-1625572804306.xlsx](https://github.com/Lora-net/lora_edge_tracker_ref_design/files/6769842/Data.flow-1625572804306.xlsx)

how I test lr1110 gnss location test?

**Comment by smtcbboulet** [comment]
Hello, 

Your tracker is not clock synchronized, it means that the GNSS can't work, the GNSS scan needs to be clock synchronized.
I think that you have a downlink issue between Tago and Actility.
I think you need to regenerate your tunnel interface authentication key.

![image](https://user-images.githubusercontent.com/61151331/125078893-4bce7c00-e0c3-11eb-8343-286ae7e4ebe5.png)
![image](https://user-images.githubusercontent.com/61151331/125078926-56891100-e0c3-11eb-9cf4-86b52fa34be0.png)

then restart your tracker in order to regenerate the clock sync request.

please check you actility console, you have to see data downlink (not only mac downlink) at the beginning.

let me know

Regards,

Benjamin

**Comment by smtcbboulet** [comment]
hello, any news ?

**Comment by smtcbboulet** [comment]
I close, please reopen if you need.

thanks,

Ben
