### ISSUE TITLE
Update application firmware in OTA mode fail

### ISSUE THREAD

**Issue by tantudaisu** [Lora-net/lora_edge_tracker_ref_design#6]
Recently bought LoRa Edg Tracker Reference Design. I followed the quick start guide and after few steps and Clicking on Update application firmware device went into  SMTC_TKR_OTA mode. After that I can not update application firmware anymore.

Did i missed something?

In SMTC_TKR_OTA mode, after reaching 99% i get the graied message "Could not update firmware" and loose connection to the device. Red led starts to blink.

![Screenshot_20210712-164113](https://user-images.githubusercontent.com/86839933/125299233-a0772e80-e331-11eb-9e3e-d1b3eb5ae92e.png)

Is there any other way to update firmware?

**Comment by smtcbboulet** [comment]
Hello, this behavior is normal, when you are in OTA, the application doesn't now the previous BLE MAC address when you asked the FOTA, because of this the smartphone can't perform the automatic BLE connection after the FOTA, normally after reached the 99% the tracker has restarted you are able to scan it (manually), you mentioned "and loose connection to the device. Red led starts to blink." meaning that your tracker has restarted, if you connect to it you should see that is has been updated. could you confirm ?

regards,

Benjamin

**Comment by tantudaisu** [comment]
I can scan it, but when i connect again, device is still in the OTA mode. 

![Screenshot_20210712-175033](https://user-images.githubusercontent.com/86839933/125308947-036cc380-e33a-11eb-9f91-b6240f672890.png)

Also can not get firmware version and other data:

![Screenshot_20210712-175100](https://user-images.githubusercontent.com/86839933/125309124-29926380-e33a-11eb-9db6-5ba8dfdcf687.png)

**Comment by smtcbboulet** [comment]
If you click on upgrade, wait the 99% then scan manually when the tracker restart, what do you see ?

**Comment by tantudaisu** [comment]
After 99% usually I get message "Could not get firmware"  Then I scan again and see the same  SMTC_TKR_OTA as in the screenshot above. Checked with STM32CUBE programmer - from 0x0800 7000 address there is no bin data.

After last try to update over the mobile app, can not scan device. Orange LED blinks and the device is in continuous reboot (every 2seconds or so).  Again check with  STM32CUBE programmer, i see that data is written  from 0x0800 7000 address, but now dev kit is continuously rebooting...

**Comment by smtcbboulet** [comment]
If you can check with STM32CUBE, you can flash the bin thanks to the SWD I guess ? did you tried to flash the official bin hosted on github or yours ? could you explain what you did from the beginning in order to I try to figure out please ?

thanks,

Ben

**Comment by tantudaisu** [comment]
I have tried to flashed both official bin files: BLE_Ota.bin and lr1110_modem_tracker_sdk.bin from github using SWD &  STM32CUBE. 

I have erased full chip flash memory first and then flashed BLE_Ota.bin Red led blinks and i can scan the dev kit using Lora Edge Config app with android phone. Dev kit is detected as SMTC_TKR_OTA. But it does not update Application Firmware as mentioned earlier.  After 99%, I still get message "Could not update firmware". 

Then i also tried to flash  lr1110_modem_tracker_sdk.bin Does not work for me.  Dev kit is in continuous reboot mode every ~2s, orange LED is  blinking.

I also updated FUS and BLE firmware provided by ST:
stm32wb5x_FUS_fw.bin
stm32wb5x_BLE_Stack_full_fw.bin

I suppose this may have some effect on OTA?

**Comment by smtcbboulet** [comment]
When the tracker reboot, both leds blink, do you see that or only one ? when the tracker starts the red led blinks meaning BLE advertisement for 30s.

the lr1110_modem_tracker_sdk.bin shall be installed a the address 0x08007000. did you do that ? otherwise you can flash the .hex file (lr1110_modem_tracker_EU868.hex) in https://github.com/Lora-net/lora_edge_tracker_ref_design/tree/master/hex_merged. it contains the bootloader and the app. please also erase the full memory with this command lines :

cd C:\Program Files\STMicroelectronics\STM32Cube\STM32CubeProgrammer\bin
STM32_Programmer_CLI.exe -c port=SWD sn=0672FF494849887767173725 -e [0 202] 

the page 202 contains the tracker context, you will have to configure again as you want after flash the .hex

for information you can't erase the page after the 202 because these sectors are protected for the M0.

let me know,

Benjamin

**Comment by tantudaisu** [comment]
I will try to flash the .hex
can i do it in  command line? what command shall i use?

**Comment by smtcbboulet** [comment]
Go where is located the .hex then type : 
STM32_Programmer_CLI.exe sn="your serial number" -c port=SWD -d lr1110_modem_loramac_EU868.hex

regards,

Benjamin

**Comment by smtcbboulet** [comment]
any news ?
